name: Build and Deploy (No Traffic)

on:
  pull_request:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - 'quest/**'
      - .github/workflows/cloudrun-*

env:
  PROJECT_ID: justin-quest
  SERVICE_NAME: quest
  REGION: us-central1
  SECRET_WORD: "foobar"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_KEY }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'
    - name: check quest
      run: ls -lrta quest/

    - name: Build and Push Image
      uses: whoan/docker-build-with-cache-action@master
      with:
        username: _json_key
        password: ${{ secrets.GCP_KEY }}
        registry: us-central1-docker.pkg.dev
        image_name: justin-quest/justin-quest/${{ env.SERVICE_NAME }}
        image_tag: ${{ github.sha }}

    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v1
      with:
        service: ${{ env.SERVICE_NAME }}
        region: ${{ env.REGION }}
        image: gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
        tag: ${{ github.sha }}
        no_traffic: true