name: Build and Deploy (All Traffic)

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - 'quest/**'
      - .github/workflows/cloudrun-*

env:
  PROJECT_ID: justin-quest
  SERVICE_NAME: quest
  REGION: us-central1

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - id: image_tag
      run: |
        echo "IMAGE_TAG=main-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          
    - id: revision_tag
      run: echo "REVISION_TAG=$(echo ${{ steps.image_tag.outputs.IMAGE_TAG }} | sed -E 's/[A-Z]/\L/g; s/(.{30}[^-]).*/\1/g; s/_/-/g; s/-+$//g')" >> $GITHUB_OUTPUT
      
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_KEY }}'
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
    - name: 'Use gcloud CLI'
      run: 'gcloud info'
    - name: Build and Push Image
      uses: whoan/docker-build-with-cache-action@master
      with:
        username: _json_key_base64
        password: ${{ secrets.GCP_KEY }}
        registry: ${{env.REGION}}-docker.pkg.dev
        image_name: justin-quest/justin-quest/${{ env.SERVICE_NAME }}
        image_tag: ${{ steps.image_tag.outputs.IMAGE_TAG }}

    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v1
      with:
        service: ${{ env.SERVICE_NAME }}
        region: ${{ env.REGION }}
        image: ${{env.REGION}}-docker.pkg.dev/justin-quest/justin-quest/${{ env.SERVICE_NAME }}:${{ steps.image_tag.outputs.IMAGE_TAG }}
        tag: ${{ steps.revision_tag.outputs.REVISION_TAG }}
        # flags: --port=3000
        revision_traffic: 'LATEST=100'
        env_vars: |-
          FRUIT=apple