name: Build and Deploy (No Traffic)

on:
  pull_request:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - 'quest/**'
      - .github/workflows/cloudrun-*

env:
  PROJECT_ID: justin-quest
  SERVICE_NAME: quest
  REGION: us-central1
  SECRET_WORD: "foobar"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_KEY }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'
    - name: Build and Push Image
      uses: whoan/docker-build-with-cache-action@master
      with:
        username: _json_key_base64
        password: ${{ secrets.GCP_KEY }}
        registry: us-central1-docker.pkg.dev
        image_name: justin-quest/justin-quest/${{ env.SERVICE_NAME }}
        image_tag: ${{ github.sha }}
    - name: Check if Cloud Run service exists
      id: check_service
      run: |
        if gcloud run services describe ${{ env.SERVICE_NAME }} --region=${{env.REGION}} --platform=managed &>/dev/null; then
          echo "service_exists=true" >> $GITHUB_OUTPUT
        else
          echo "service_exists=false" >> $GITHUB_OUTPUT
        fi

    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v1
      if: steps.check_service.outputs.service_exists == 'true'
      with:
        service: ${{ env.SERVICE_NAME }}
        region: ${{ env.REGION }}
        image: gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
        tag: ${{ github.sha }}
        no_traffic: true